#ifndef LIBXSMM_CONFIG_H
#define LIBXSMM_CONFIG_H

#define LIBXSMM_CONFIG_VERSION "1.8.1-102"
#define LIBXSMM_CONFIG_BRANCH "master"
#define LIBXSMM_CONFIG_VERSION_MAJOR 1
#define LIBXSMM_CONFIG_VERSION_MINOR 8
#define LIBXSMM_CONFIG_VERSION_UPDATE 1
#define LIBXSMM_CONFIG_VERSION_PATCH 102

#define LIBXSMM_CONFIG_ALIGNMENT 64
#define LIBXSMM_CONFIG_PREFETCH -1
#define LIBXSMM_CONFIG_MAX_MNK 2097152
#define LIBXSMM_CONFIG_MAX_M 128
#define LIBXSMM_CONFIG_MAX_N 128
#define LIBXSMM_CONFIG_MAX_K 128
#define LIBXSMM_CONFIG_AVG_M 64
#define LIBXSMM_CONFIG_AVG_N 64
#define LIBXSMM_CONFIG_AVG_K 64
#define LIBXSMM_CONFIG_FLAGS 0
#define LIBXSMM_CONFIG_ILP64 0
#define LIBXSMM_CONFIG_ALPHA 1
#define LIBXSMM_CONFIG_BETA 1
#define LIBXSMM_CONFIG_WRAP 2
#define LIBXSMM_CONFIG_SYNC 1
#define LIBXSMM_CONFIG_JIT 1


#endif


