test: test.cpp
	g++ -o test.out -Wall test.cpp -std=c++11 -pthread

test2: test2.cpp
	g++ -o test2.out -Wall test2.cpp -std=c++11 -pthread

test3: test3.cpp
	g++ -o test3.out -Wall test3.cpp -std=c++11 -pthread

